"""
Malawi Flood EWS — Data Sync
Downloads model files and latest GeoTIFFs from Google Drive to Render.
Run once on startup, then auto_pipeline.py handles inference.

Usage:
    python data_sync.py --models-only     # first deploy — download models
    python data_sync.py --latest          # download latest auto exports
    python data_sync.py --all             # download everything
"""

import os
import json
import logging
import argparse
from pathlib import Path

logging.basicConfig(level=logging.INFO,
                    format='%(asctime)s [%(levelname)s] %(message)s')
logger = logging.getLogger(__name__)

# Local storage on Render
LOCAL_FOLDER = os.getenv('GDRIVE_FOLDER',
               '/opt/render/project/data/MalawiFloodEWS')

# Google Drive file IDs — fill these in after uploading to Drive
# Get ID from Drive share link: drive.google.com/file/d/FILE_ID/view
DRIVE_FILES = {
    # Models (static — only download once)
    'model_rf_phase3b.pkl':     os.getenv('DRIVE_ID_RF',      ''),
    'model_xgb_phase3b.pkl':    os.getenv('DRIVE_ID_XGB',     ''),
    'scaler_phase3b.pkl':       os.getenv('DRIVE_ID_SCALER',  ''),
    'imputer_phase3b.pkl':      os.getenv('DRIVE_ID_IMPUTER', ''),
    'feature_names.npy':        os.getenv('DRIVE_ID_FEATURES',''),
    # Static terrain (download once)
    'malawi_terrain_features.tif': os.getenv('DRIVE_ID_TERRAIN',''),
    # Historical events (for dashboard display)
    'malawi_flood_mask_idai_2019_v10.tif':
        os.getenv('DRIVE_ID_IDAI_MASK', ''),
    'malawi_s1_after_idai_db_v10.tif':
        os.getenv('DRIVE_ID_IDAI_SAR',  ''),
    'malawi_chirps_rainfall_idai_2019.tif':
        os.getenv('DRIVE_ID_IDAI_RAIN', ''),
}

MODEL_FILES = [
    'model_rf_phase3b.pkl',
    'model_xgb_phase3b.pkl',
    'scaler_phase3b.pkl',
    'imputer_phase3b.pkl',
    'feature_names.npy',
]

STATIC_FILES = [
    'malawi_terrain_features.tif',
    'malawi_flood_mask_idai_2019_v10.tif',
    'malawi_s1_after_idai_db_v10.tif',
    'malawi_chirps_rainfall_idai_2019.tif',
]


def ensure_folder(folder: str) -> None:
    Path(folder).mkdir(parents=True, exist_ok=True)
    logger.info(f"Storage folder: {folder}")


def download_file(file_id: str, dest_path: str) -> bool:
    """Download a file from Google Drive using gdown."""
    if not file_id:
        logger.warning(f"No Drive ID for {os.path.basename(dest_path)} — skipping")
        return False
    if os.path.exists(dest_path):
        logger.info(f"Already exists: {os.path.basename(dest_path)}")
        return True
    try:
        import gdown
        url = f'https://drive.google.com/uc?id={file_id}'
        gdown.download(url, dest_path, quiet=False)
        logger.info(f"Downloaded: {os.path.basename(dest_path)}")
        return True
    except Exception as e:
        logger.error(f"Download failed {os.path.basename(dest_path)}: {e}")
        return False


def download_models(folder: str) -> None:
    """Download model pkl files."""
    logger.info("Downloading model files...")
    for fname in MODEL_FILES:
        fid  = DRIVE_FILES.get(fname, '')
        dest = os.path.join(folder, fname)
        download_file(fid, dest)


def download_static(folder: str) -> None:
    """Download static GeoTIFF files."""
    logger.info("Downloading static GeoTIFFs...")
    for fname in STATIC_FILES:
        fid  = DRIVE_FILES.get(fname, '')
        dest = os.path.join(folder, fname)
        download_file(fid, dest)


def download_latest_auto(folder: str) -> None:
    """
    Download the most recent auto_YYYYMMDD exports.
    These are generated by AUTO_RollingDetection.js every 12 days.
    File IDs change each run — use Drive API or manual update.
    """
    logger.info("Latest auto exports must be synced via Drive API.")
    logger.info("For now: manually upload auto_*.tif files to Render storage")
    logger.info("or connect Drive API with service account credentials.")


def verify_downloads(folder: str) -> dict[str, bool]:
    """Check which required files are present."""
    required = MODEL_FILES + STATIC_FILES
    status   = {}
    for fname in required:
        path = os.path.join(folder, fname)
        status[fname] = os.path.exists(path)
        icon = '✅' if status[fname] else '❌'
        logger.info(f"  {icon} {fname}")
    return status


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--models-only', action='store_true')
    parser.add_argument('--static',      action='store_true')
    parser.add_argument('--latest',      action='store_true')
    parser.add_argument('--all',         action='store_true')
    parser.add_argument('--verify',      action='store_true')
    parser.add_argument('--folder', type=str, default=LOCAL_FOLDER)
    args = parser.parse_args()

    ensure_folder(args.folder)

    if args.models_only or args.all:
        download_models(args.folder)
    if args.static or args.all:
        download_static(args.folder)
    if args.latest or args.all:
        download_latest_auto(args.folder)
    if args.verify or args.all:
        print("\nFile status:")
        verify_downloads(args.folder)